### PR TITLE
add classifier inside pom

### PR DESCRIPTION
**Pull request by bdbogjoe**
the classifier is actually not include inside dependency, i created another issue for this : https://jira.grails.org/browse/GPRELEASE-62

### CODE REVIEW

**Comment by asans** [comment]
This should be merged as classifier is an important part of the maven repository.  I could not get plugin to work well when making use of repository classifiers.

**Comment by bdbogjoe** [comment]
Waiting....

**Comment by asans** [comment]
@graemerocher Unfortunately, I tested this on Grails 2.4.4 and it did not work.  When I looked into the issue further on why the classifier is null and not set, I found that AetherDependencyManager appears not to set the classifier when creating the Dependency object.  

The code merged here for release plugin should be correct, so I think the release plugin is fine.  It appears to be a bug in Grails itself in this case.

**Comment by bdbogjoe** [comment]
This issue should be fixed with this pull request https://github.com/grails/grails-core/pull/564

Try with grails 2.5.1

**Comment by asans** [comment]
Yup that change should fix it.  Great news.

**Pull request merged**
